### PR TITLE
Authentication

### PR DESCRIPTION
**Pull request by thinktwice13**
### Summary
- e2e working auth example (`/authexample` on client)
- passport *local* strategy
- server `/login` and `/register` routes logic with tests
- add JWT encoding/decoding/verification utils
- save and check hashed passwords using `bcrypt`
- updated graphql resolvers with tests
- pass tokens in graphql `context` param through `ApolloProvider`
- updated ESLint config
- using `babel-preset-stage-0` on client to enable testing arrow functions in components

#### New requirements:
- Reseed development database
- `JWT_SECRET` in `/server/src/config/keys/` dev.js and test.js
- Assumes port `4000` for api server

### CODE REVIEW

**Review by aaayumi — COMMENTED** [review]
1. I found many commented out code. Do you want to keep them all? It might be better to delete if we won't use them. 
2. I guess that the design of login/signup page are not completed yet. Once they are done, inline styling can be replaced with styled component?

**Comment by thinktwice13** [comment]
@aaayumi 
1. I left some commented areas in because we're not yet sure if we're going to use them (like passport middleware). But, it's ok to remove them, I can get them back from an old commit if needed.

2. I put the client authentication up just to test things out and it can serve as a reference to how things are behaving for anyone who is going to work on the real sign in page. AuthExample component should be removed entirely once we have the real one.

**Comment by fredhawk** [comment]
Works for me, there are some kinks with the seeds not working since those passwords aren't encoded in the database and therefor can not be decoded so it fails on them.
But outside of that it works very well. 👍

**Comment by thinktwice13** [comment]
@osycon 
Hmm, you're right. I hardcoded only one user seed (mail@mail.com:12354) and its password is hashed as well as of any new users you register, but none of the generated seeds are. 
I can change that.

**Review by fredhawk — APPROVED** [review]
Works nicely! :+1:

**Pull request merged**
