### PR TITLE
Project setup

### LINKED ISSUE #7: Add ESLint config

### LINKED ISSUE #22: Add client setup with create-react-app

### LINKED ISSUE #30: Setup CORS
Because the API and the client run on different ports in development, there will be an Cross Origin Resource Sharing error

### PR DESCRIPTION
**Pull request by thinktwice13**
## Summary
- ESlint config
- Server `index.js` moved to `/server/src`
- Example server e2e test
- CI for the development branch
- Use CORS
- Use Babel on server

Closes #7 
Closes #22 
Closes #30

### CODE REVIEW

**Review by thomaslombart — DISMISSED** [review]

**Comment by fredhawk** [comment]
When I test this this setup for eslint/prettier changes from what you say it does. It does not add trailing commas for me and it puts parameters in arrays and objects on own lines instead of same line. I have prettier disabled in my editor so it isn't doing it. 
Is it working for everyone else but me?

**Comment by thomaslombart** [comment]
That's weird. All is working fine for me.

**Comment by thinktwice13** [comment]
@osycon Working for me. Block the Merge until we get this resolved. I'd also like to hear from @aaayumi.
@thomlom `.eslintrc.json` needs to be moved to the root and dependencies installed in the client projects. Working on it

**Review by fredhawk — CHANGES_REQUESTED** [review]
When I test this this setup for eslint/prettier changes from what you say it does. It does not add trailing commas for me and it puts parameters in arrays and objects on own lines instead of same line. I have prettier disabled in my editor so it isn't doing it. 
Is it working for everyone else but me?
Blocking this for now.

**Comment by thinktwice13** [comment]
If  anyone is having issues starting or testing the client app due to `Error: ENOSPC`: https://stackoverflow.com/questions/22475849/node-js-error-enospc/32600959#32600959

**Pull request closed without merging**
